{% set name = "pyspnego" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspnego-{{ version }}.tar.gz
  sha256: c45f95cd0877b6354b4e3e9ad49df30bc3d9f4f6730fc32e90eb2e32b1fef34d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cryptography
    - cython
    - pip
  run:
    - python
    - cryptography
    - ruamel.yaml
  run_constrained:
    - python-gssapi >=1.5.0  # [not win]

test:
  imports:
    - spnego
    - spnego._ntlm_raw
    - spnego._sspi_raw  # [win]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
