{% set name = "pyspnego" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspnego-{{ version }}.tar.gz
  sha256: 9a22c23aeae7b4424fdb2482450d3f8302ac012e2644e1cfe735cf468fcd12ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cryptography
    - ruamel.yaml
    - sspilib >=0.1.0  # [win]
  run_constrained:
    - python-gssapi >=1.6.0  # [not win]
    - krb5 >=0.3.0  # [not win]

test:
  imports:
    - spnego
    - spnego._ntlm_raw
    - spnego._sspi_raw  # [win]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
